import type { Metadata } from 'next'
import ThemeRegistry from '../../theme/ThemeRegistry'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body
          className={`antialiased`}
          style={{
            height: '100%',
            width: '100%',
            scrollBehavior: 'smooth'
          }}
        >
          {children}
        </body>
      </ThemeRegistry>
    </html>
  )
}
